export SERVER_NAME='Enshrouded Server'
export SERVER_SLOTS=4
export SERVER_PASSWORD=xxx
export GAME_PORT=15636
export QUERY_PORT=15637
export NOIP_USER=xxx
export NOIP_PWD=xxx
export MEGA_USER=xxx
export MEGA_PWD=xxx
export BACKUP_REMOTE_DIR=xxx
export MAX_IDLE_MINUTES=30